services:
  - type: web
    name: mqtt-broker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Health check using HTTP on port 8080
    healthCheckPath: /
    # Let Render.com manage ports
    ports:
      - protocol: tcp
        containerPort: 1883
      - protocol: tcp
        containerPort: 9001
      - protocol: tcp
        containerPort: 8080
