services:
  - type: web
    name: mqtt-broker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 1883
    # Health check endpoint (optional, Mosquitto doesn't have HTTP endpoint by default)
    healthCheckPath: /
    # Render will assign a port, but we need to use MQTT ports
    ports:
      - protocol: tcp
        containerPort: 1883
        externalPort: 1883
      - protocol: tcp
        containerPort: 9001
        externalPort: 9001
