services:
  - type: web
    name: mqtt-broker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # MQTT doesn't use HTTP, disable health checks
    healthCheckPath: null
    # Let Render.com manage ports
    ports:
      - protocol: tcp
        containerPort: 1883
      - protocol: tcp
        containerPort: 9001
